Repository graasp/graasp-player, pull requests merged in 2022-11, with the labels that each got.

#146 fix: change page title for GA
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: feature

#152 feat: update workflows
  .github/workflows/cdelivery-s3-caller.yml
  .github/workflows/cdeployment-s3-caller.yml
  .github/workflows/cintegration-s3-caller.yml
  .github/workflows/cypress.yml
  .github/workflows/update-staging-version.yml
  cypress/integration/main.spec.js
  cypress/support/commands.js
  cypress/support/server.js
  public/index.html
  src/components/common/BuilderButton.js
Labels: chore

#159 Fix auto-resize: bump @graasp/ui
  package.json
  yarn.lock
Labels: bug
