Repository graasp/graasp-player, pull requests merged in 2023-02, with the labels that each got.

#186 chore: update package test scripts and yarn version
  .yarn/releases/yarn-3.2.4.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  package.json
  src/config/constants.ts
  yarn.lock
Labels: chore

#185 ci: add concurency setting to cancel previous running workflows
  .github/workflows/cdelivery-s3-caller.yml
  .github/workflows/cdeployment-s3-caller.yml
  .github/workflows/cintegration-s3-caller.yml
  .github/workflows/cypress.yml
Labels: chore

#184 feat: add platform switch to player
  package.json
  src/components/main/HeaderNavigation.tsx
  src/components/main/Home.js
  src/components/main/MainScreen.js
  src/config/selectors.js
  yarn.lock
Labels: feature

#191 190 improve arrow tree view
  package.json
  src/components/common/Tree/CustomContentTree.js
  src/components/common/Tree/CustomLabel.tsx
  src/components/common/Tree/Tree.js
  yarn.lock
Labels: bug

#198 feat: remove builder button
  cypress/e2e/main.cy.js
  src/components/common/SideContent.js
Labels: feature
