Repository graasp/graasp-player, pull requests merged in 2023-01, with the labels that each got.

#170 feat: add etherpad view
  package.json
  src/components/common/Item.js
  src/enums/itemTypes.js
  yarn.lock
Labels: feature

#174 fix: h5p revert to default iframe
  package.json
  yarn.lock
Labels: bug

#178 fix: update chatbox with mention fix
  package.json
  src/components/common/Item.js
  src/components/common/SideContent.js
  src/components/common/Tree/CustomTreeShortcutItem.js
  tsconfig.json
  yarn.lock
Labels: chore

#182 fix: update @graasp/query-client
  package.json
  yarn.lock
Labels: bug
