Repository graasp/graasp-player, pull requests merged in 2023-09, with the labels that each got.

#344 feat: keep current window location on login of forbidden screen
  src/config/constants.ts
  src/modules/item/ItemForbiddenScreen.tsx
  src/modules/userSwitch/UserSwitchWrapper.tsx
Labels: feature

#349 fix: improve hidden pdf display
  src/modules/common/HiddenWrapper.tsx
Labels: bug :beetle:, ui :eyes:

#345 fix: allow multiple etherpads to be opened simultaneously
  package.json
  yarn.lock
Labels: bug :beetle:

#351 fix: do not show hidden items to admin and writers
  cypress/e2e/hidden.cy.ts
  cypress/fixtures/items.ts
  src/modules/item/Item.tsx
Labels: improvement

#354 fix: collapsible shortcuts
  .github/workflows/cypress.yml
  cypress/e2e/collapsed.cy.ts
  cypress/fixtures/items.ts
  package.json
  src/config/selectors.ts
  src/modules/item/Item.tsx
  yarn.lock
Labels: bug :beetle:
