Repository graasp/graasp-player, pull requests merged in 2023-03, with the labels that each got.

#203 feat: add document styles in Player
  .eslintrc
  cypress/e2e/main.cy.js
  package.json
  src/components/main/HeaderNavigation.tsx
  src/components/main/ItemForbiddenScreen.tsx
  yarn.lock
Labels: feature

#213 docs: improve doc related to env files
  README.md
Labels: documentation

#221 fix(ui): add missing inclusion of styles
  package.json
  src/main.tsx
  src/modules/item/Item.tsx
  yarn.lock
Labels: bug
