Repository graasp/graasp-player, pull requests merged in 2024-10, with the labels that each got.

#862 chore(main): release 2.20.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#875 fix: update deps
  cypress/e2e/redirections.cy.ts
  package.json
  src/modules/layout/PageWrapper.tsx
  src/modules/pages/itemPage/ItemPage.tsx
  yarn.lock
Labels: dependencies

#876 feat: add auto login
  cypress/e2e/autoLogin.cy.ts
  cypress/support/commands.ts
  src/App.tsx
  src/config/paths.ts
  src/config/selectors.ts
  src/langs/constants.ts
  src/langs/en.json
  src/modules/pages/AutoLogin.tsx
Labels: feature

#871 chore(main): release 2.21.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#880 fix: update mui version to v6
  cypress/support/commands.ts
  cypress/support/server.ts
  package.json
  src/modules/pages/HomePage.tsx
  src/modules/rightPanel/SideContent.tsx
  yarn.lock
Labels: dependencies

#884 chore(main): release 2.21.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#887 fix: move page wrapper where the ids are known
  cypress/e2e/navigation.cy.ts
  src/App.tsx
Labels: bug :beetle:
