Repository graasp/graasp-player, pull requests merged in 2024-09, with the labels that each got.

#833 chore(main): release 2.18.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#849 fix: pins should not be inherited
  cypress/e2e/pinned.cy.ts
  cypress/fixtures/items.ts
  cypress/support/server.ts
  src/modules/item/Item.tsx
  src/modules/navigation/tree/LoadingTree.tsx
  src/modules/rightPanel/SideContent.tsx
Labels: bug :beetle:

#851 fix: update eslint to v9
  .eslintignore
  .eslintrc.json
  cypress/fixtures/apps.ts
  cypress/fixtures/useCases/staticElectricity.ts
  cypress/support/e2e.ts
  eslint.config.mjs
  package.json
  src/utils/tree.ts
  yarn.lock
Labels: chore

#855 fix: eslint@v9 error with vite-plugin-checker
  vite.config.ts
Labels: bug :beetle:

#860 chore(main): release 2.19.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#861 fix: remove usage of `false` in component return
  src/modules/item/Item.tsx
  src/modules/navigationIsland/ChatButton.tsx
  src/modules/navigationIsland/GeolocationButton.tsx
  src/modules/navigationIsland/NavigationIsland.tsx
  src/modules/navigationIsland/PinnedItemsButton.tsx
  src/modules/navigationIsland/PreviousNextButtons.tsx
  src/modules/pages/HomePage.tsx
Labels: chore
