Repository graasp/graasp-player, pull requests merged in 2024-04, with the labels that each got.

#596 feat: improve player
  package.json
  src/modules/item/FolderCard.tsx
  src/modules/item/Item.tsx
  src/modules/item/PinnedFolderItem.tsx
  src/modules/navigation/HomeNavigation.tsx
  src/modules/navigation/ItemNavigation.tsx
  src/modules/navigation/tree/LoadingTree.tsx
  src/modules/navigation/tree/TreeView.tsx
  src/modules/navigationIsland/PinnedItemsButton.tsx
  src/modules/rightPanel/SideContent.tsx
  src/utils/item.ts
  yarn.lock
Labels: improvement

#603 fix: Fix tree crash bug
  src/modules/navigation/ItemNavigation.tsx
Labels: bug :beetle:

#602 fix: rename chatbox title
  src/langs/constants.ts
  src/langs/en.json
  src/langs/fr.json
  src/modules/rightPanel/SideContent.tsx
Labels: improvement

#640 feat: add container and header for folders
  README.md
  cypress/e2e/collapsed.cy.ts
  cypress/e2e/pinned.cy.ts
  cypress/fixtures/documents.ts
  cypress/fixtures/items.ts
  cypress/fixtures/useCases/staticElectricity.ts
  cypress/support/integrationUtils.ts
  package.json
  src/config/selectors.ts
  src/langs/constants.ts
  src/langs/en.json
  src/modules/common/ItemCard.tsx
  src/modules/errors/FallbackComponent.tsx
  src/modules/item/Item.tsx
  src/modules/item/SectionHeader.tsx
  src/modules/layout/PageWrapper.tsx
  src/modules/main/ItemGrid.tsx
  src/modules/navigation/ItemNavigation.tsx
  src/modules/navigationIsland/ChatButton.tsx
  src/modules/navigationIsland/CustomButtons.tsx
  src/modules/navigationIsland/NavigationIsland.tsx
  src/modules/navigationIsland/PinnedItemsButton.tsx
  src/modules/navigationIsland/PreviousNextButtons.tsx
  src/modules/pages/HomePage.tsx
  src/modules/rightPanel/SideContent.tsx
  src/modules/rightPanel/SideDrawer.tsx
  src/modules/userSwitch/MemberAvatar.tsx
  vite.config.ts
  yarn.lock
Labels: feature
