Repository graasp/graasp-player, pull requests merged in 2024-06, with the labels that each got.

#737 fix: app resizing issue
  package.json
  src/modules/item/Item.tsx
  yarn.lock
Labels: bug :beetle:

#742 fix: duplicated island
  cypress/e2e/island.cy.ts
  cypress/fixtures/items.ts
  src/config/selectors.ts
  src/modules/item/Item.tsx
  src/modules/navigationIsland/NavigationIsland.tsx
Labels: bug :beetle:

#746 fix: app max height
  package.json
  yarn.lock
Labels: bug :beetle:

#752 fix: add geolocation button back
  cypress/e2e/island.cy.ts
  src/modules/navigationIsland/NavigationIsland.tsx
Labels: chore

#772 fix: container width and image sizing
  cypress/support/integrationUtils.ts
  package.json
  src/modules/item/Item.tsx
  yarn.lock
Labels: improvement

#774 fix: internal link crashes navigation
  cypress/e2e/navigation.cy.ts
  cypress/support/e2e.ts
  src/config/selectors.ts
  src/langs/constants.ts
  src/langs/en.json
  src/modules/navigation/tree/TreeErrorBoundary.tsx
  src/modules/navigation/tree/TreeView.tsx
Labels: bug :beetle:

#771 chore(main): release 2.15.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#778 fix: update ui and dependencies
  cypress/support/server.ts
  package.json
  src/modules/item/Item.tsx
  yarn.lock
Labels: bug :beetle:
