Repository graasp/graasp-player, pull requests merged in 2024-01, with the labels that each got.

#444 fix: update chatbox
  package.json
  src/modules/chatbox/Chatbox.tsx
  yarn.lock
Labels: dependencies

#421 feat: treeview component
  cypress/e2e/header.cy.ts
  cypress/e2e/main.cy.ts
  cypress/e2e/navigation.cy.ts
  cypress/e2e/ws.cy.ts
  cypress/fixtures/items.ts
  cypress/fixtures/useCases/staticElectricity.ts
  cypress/support/commands.ts
  cypress/support/constants.ts
  cypress/support/integrationUtils.ts
  cypress/support/server.ts
  package.json
  src/config/selectors.ts
  src/langs/constants.ts
  src/langs/en.json
  src/langs/fr.json
  src/modules/item/ItemNavigation.tsx
  src/modules/item/MainScreen.tsx
  src/modules/main/ItemGrid.tsx
  src/modules/pages/HomePage.tsx
  src/modules/pages/ItemPage.tsx
  src/modules/rightPanel/SideContent.tsx
  src/modules/tree/CustomContentTree.tsx
  src/modules/tree/CustomLabel.tsx
  src/modules/tree/CustomTreeItem.tsx
  src/modules/tree/CustomTreeShortcutItem.tsx
  src/modules/tree/DynamicTreeView.tsx
  src/modules/tree/Node.tsx
  src/modules/tree/TreeView.tsx
  src/utils/item.ts
  src/utils/tree.ts
  yarn.lock
Labels: improvement

#459 fix: add build workflow
  .github/workflows/build.yml
  .github/workflows/update-staging-version.yml
Labels: build

#442 feat(ui): responsive design improvements
  src/modules/header/HeaderNavigation.tsx
  src/modules/item/MainScreen.tsx
  src/modules/pages/ItemPage.tsx
Labels: ui :eyes:

#479 fix: add return in `ItemGrid`
  src/modules/main/ItemGrid.tsx
Labels: chore

#483 fix: handle undefined childrenOrder
  package.json
  src/utils/tree.ts
  yarn.lock
Labels: bug :beetle:
