Repository graasp/graasp-player, pull requests merged in 2024-03, with the labels that each got.

#541 feat: update ui to update the description's position
  package.json
  src/modules/item/Item.tsx
  yarn.lock
Labels: feature

#574 fix: add error boundary and fallback component
  src/Root.tsx
  src/langs/constants.ts
  src/langs/en.json
  src/modules/errors/FallbackComponent.tsx
Labels: chore, improvement

#573 fix: navigation crash on expand non-present parent ids
  cypress/e2e/navigation.cy.ts
  cypress/fixtures/items.ts
  src/modules/navigation/tree/TreeView.tsx
Labels: bug :beetle:

#576 feat: create navigation island
  .github/workflows/cypress.yml
  cypress/e2e/apps.cy.ts
  cypress/e2e/chatbox.cy.ts
  cypress/e2e/collapsed.cy.ts
  cypress/e2e/hidden.cy.ts
  cypress/e2e/island.cy.ts
  cypress/e2e/main.cy.ts
  cypress/e2e/pinned.cy.ts
  cypress/fixtures/items.ts
  package.json
  src/App.tsx
  src/config/paths.ts
  src/contexts/LayoutContext.tsx
  src/langs/constants.ts
  src/langs/en.json
  src/modules/common/ItemCard.tsx
  src/modules/item/Item.tsx
  src/modules/item/MainScreen.tsx
  src/modules/item/NavigationButton.tsx
  src/modules/layout/PageWrapper.tsx
  src/modules/navigation/ItemNavigation.tsx
  src/modules/navigation/tree/TreeView.tsx
  src/modules/navigationIsland/ChatButton.tsx
  src/modules/navigationIsland/NavigationIsland.tsx
  src/modules/navigationIsland/PinnedItemsButton.tsx
  src/modules/navigationIsland/PreviousNextButtons.tsx
  src/modules/pages/ItemPage.tsx
  src/modules/rightPanel/SideContent.tsx
  vite.config.ts
  yarn.lock
Labels: feature

#593 fix: notifs should stack
  src/Root.tsx
Labels: improvement

#594 fix: add redirection url on home page authorization
  cypress/e2e/redirections.cy.ts
  src/App.tsx
  src/config/selectors.ts
  src/modules/item/ItemForbiddenScreen.tsx
Labels: bug :beetle:
